# Generated by Django 4.2.21 on 2025-05-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='symbol',
        ),
        migrations.AddField(
            model_name='product',
            name='client_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف العميل'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='abbreviation',
            field=models.CharField(default=0, max_length=10, verbose_name='اختصار الوحدة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='amazon_sku',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رمز المنتج على أمازون'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_fbm',
            field=models.BooleanField(default=False, verbose_name='FBM'),
        ),
    ]
