# Generated by Django 4.2.21 on 2025-05-31 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_productunit_symbol_product_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='client_id',
        ),
    ]
