# Generated by Django 4.2.20 on 2025-05-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_access_key', models.CharField(max_length=255, verbose_name='AWS Access Key')),
                ('aws_secret_key', models.CharField(max_length=255, verbose_name='AWS Secret Key')),
                ('role_arn', models.CharField(max_length=255, verbose_name='Role ARN')),
                ('lwa_client_id', models.CharField(max_length=255, verbose_name='LWA Client ID')),
                ('lwa_client_secret', models.CharField(max_length=255, verbose_name='LWA Client Secret')),
                ('refresh_token', models.CharField(max_length=255, verbose_name='Refresh Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات أمازون',
                'verbose_name_plural': 'إعدادات أمازون',
            },
        ),
    ]
