# Generated by Django 4.2.20 on 2025-05-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonsettings',
            name='refresh_token',
            field=models.CharField(max_length=1000, verbose_name='Refresh Token'),
        ),
    ]
