# Generated by Django 4.2.21 on 2025-05-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_integration', '0002_alter_amazonsettings_refresh_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amazonsettings',
            options={'ordering': ['client_name'], 'verbose_name': 'إعدادات أمازون', 'verbose_name_plural': 'إعدادات أمازون'},
        ),
        migrations.AddField(
            model_name='amazonsettings',
            name='client_id',
            field=models.CharField(default=0, max_length=100, unique=True, verbose_name='معرف العميل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amazonsettings',
            name='client_name',
            field=models.CharField(default=0, max_length=255, verbose_name='اسم العميل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amazonsettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='amazonsettings',
            name='marketplace_id',
            field=models.CharField(default='ATVPDKIKX0DER', max_length=50, verbose_name='Marketplace ID'),
        ),
    ]
