# Generated by Django 4.2.21 on 2025-05-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_integration', '0003_alter_amazonsettings_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonsettings',
            name='aws_access_key',
        ),
        migrations.RemoveField(
            model_name='amazonsettings',
            name='aws_secret_key',
        ),
        migrations.RemoveField(
            model_name='amazonsettings',
            name='lwa_client_id',
        ),
        migrations.RemoveField(
            model_name='amazonsettings',
            name='lwa_client_secret',
        ),
        migrations.RemoveField(
            model_name='amazonsettings',
            name='role_arn',
        ),
        migrations.AlterField(
            model_name='amazonsettings',
            name='marketplace_id',
            field=models.CharField(choices=[('A1AM78C64UM0Y8', 'مصر'), ('A2VIGQ35RCS4UG', 'السعودية'), ('A2VIGQ35RCS4UG', 'الإمارات')], default='A1AM78C64UM0Y8', max_length=50, verbose_name='سوق أمازون'),
        ),
    ]
