# Generated by Django 4.2.21 on 2025-05-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_integration', '0004_remove_amazonsettings_aws_access_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonsettings',
            name='marketplace_id',
            field=models.CharField(choices=[('A1AM78C64UM0Y8', 'مصر'), ('A2VIGQ35RCS4UG', 'السعودية'), ('A2NGVSA5CAHHU9', 'الإمارات')], default='A1AM78C64UM0Y8', max_length=50, verbose_name='سوق أمازون'),
        ),
    ]
