# Generated by Django 4.2.21 on 2025-05-31 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_integration', '0005_alter_amazonsettings_marketplace_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amazonsettings',
            options={'verbose_name': 'إعدادات أمازون', 'verbose_name_plural': 'إعدادات أمازون'},
        ),
        migrations.RemoveField(
            model_name='amazonsettings',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='amazonsettings',
            name='client_name',
        ),
    ]
