# Generated by Django 4.2.21 on 2025-05-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_integration', '0006_alter_amazonsettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_access_key', models.CharField(max_length=255, verbose_name='AWS Access Key')),
                ('aws_secret_key', models.CharField(max_length=255, verbose_name='AWS Secret Key')),
                ('role_arn', models.CharField(max_length=255, verbose_name='Role ARN')),
                ('lwa_client_id', models.CharField(max_length=255, verbose_name='LWA Client ID')),
                ('lwa_client_secret', models.CharField(max_length=255, verbose_name='LWA Client Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات التطبيق',
                'verbose_name_plural': 'إعدادات التطبيق',
            },
        ),
    ]
